### ISSUE TITLE
Documentation rendering: docstring formatting not as intended

### ISSUE THREAD

**Issue by gully** [ladsantos/p-winds#39]
Hi! 👋  Great package here 🙏 

I noticed a teeny-tiny rendering issue on the documentation page.

The dtype information does not appear to render as Monospace as intended in the **Parameters** docstring.  The double backticks remain as plain text backticks:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/860227/222763776-2e93e105-8d57-4808-a887-4c63aea4dad7.png">

I was able to make the Monospace font render as intended by :
1. swapping the order of the colon from the end:
```plaintext
temperature (``float``):
```
to the colon in between the two text fields:
```plaintext
temperature : ``float``
```
and,
2. Upgrading to a recent `sphinx_rtd_theme=1.2.0` from the previous default on my system `0.4.3`

<img width="497" alt="image" src="https://user-images.githubusercontent.com/860227/222767101-1030e7a6-b514-4b5f-8eae-bb7f61d4485e.png">

**Comment by ladsantos** [comment]
Issue is fixed in [``613c38d``](https://github.com/ladsantos/p-winds/commit/613c38df1c7d0051ee7dd98eda0502dd3317f724).
