### ISSUE TITLE
Render math in docstrings?

### ISSUE THREAD

**Issue by gully** [ladsantos/p-winds#40]
Do folks here have a preference on putting some of the math in the docstrings?  Here is a simple demo:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/860227/222782442-ef6fbac5-7abb-4762-b81b-e6668d4c4637.png">

The main downside is that the Jupyter docstring does not render math, and so there's a bunch of unformatted $\LaTeX$, which can be distracting:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/860227/222783141-efcdbaa8-d642-43ff-a474-ba0c45448b0b.png">

I suppose it comes down to whether most folks use the online docs or the Jupyter quick-look, and of course the developer time to copy-and-paste over the relevant latex.

**Comment by ladsantos** [comment]
Personally, for details of a code I usually go to the ReadTheDocs page. I use the Jupyter docstring lookup mostly to remind myself of input parameters. I will do some digging and see what I can come up with.
