### ISSUE TITLE
Issue with the hydrogen rates

### ISSUE THREAD

**Issue by LarsKlijn** [ladsantos/p-winds#43]
Hi Leonardo,

When checking my hydrogen rates, I think I found a small bug. 
Line 560 of the hydrogen module:
`final_alpha_rec = recombination(temperature) * k2_abs * final_rho * \`
I think `recombination(temperature)` shouldn't be there, as it is already in the `k2_abs` term.

Cheers,

Lars

**Comment by ladsantos** [comment]
Thanks, Lars! This is now corrected in commit [`39742ff`](https://github.com/ladsantos/p-winds/commit/39742ffd33920ae17b725758fb6667f37bef359e).
