### ISSUE TITLE
Width of the Gaussian part of the Voigt profile

### ISSUE THREAD

**Issue by dlinssen** [ladsantos/p-winds#46]
Hi!

So I've been looking at the formulas for the width of the Gaussian part of the Voigt profile, and I think there might be a factor 2 in the p-winds implementation that shouldn't be there. Eq. 16 of the p-winds paper is taken from Eq. 16 of Lampón et al. (2020) and reads 

$\alpha = \frac{\nu_0}{c} \sqrt{\frac{2 k_B T}{m_{He}}}$

however, Lampón calls this $\alpha_D$ the "Doppler line width", and comparing his Eq. 15 with the definition of a Gaussian indicates that his $\alpha_D$ is actually not equal to the standard deviation $\sigma$, but to $\sqrt{2} \sigma$. The `scipy.voigt_profile()` that p-winds uses expects the standard deviation, so I think instead it should be passed $\frac{\nu_0}{c} \sqrt{\frac{k_B T}{m_{He}}}$. 
This would then also be consistent with Eq. 21 of Oklopcic&Hirata (2018), which uses $HWHM = \sqrt{\frac{2 ln 2 kT_0}{m_{He}}}\frac{\nu_0}{c}$, where the HWHM is related to the standard deviation by a factor $\sqrt{2ln2}$.

(Similarly, I think the turbulence term should be modified to $v_{turb}^2 = \frac{5kT}{6m}$)

Perhaps I am overlooking something, so if someone could verify, that would be great!
Dion

**Comment by ladsantos** [comment]
Thanks for pointing this out! The bug was corrected in commit [`372ba57`](https://github.com/ladsantos/p-winds/commit/372ba57ba16a094d134eab7540916cb5e8ba3200).
