### ISSUE TITLE
(potential enhancement) Add current working directory functionality to fluid.py

### ISSUE THREAD

**Issue by mls1052** [ladsantos/p-winds#47]
In [p-winds v2.0 beta](https://github.com/ladsantos/p-winds/releases/tag/v2.0.0beta), under the function [ates_model in fluid.py, lines 239-243 create](https://github.com/ladsantos/p-winds/blob/a829f1c837d7ae279b6db0282d227acd0b7b0fd0/p_winds/fluid.py#L238-L243) four .txt files:

``` 
if load_ic is True:
        shutil.copyfile('output/Hydro_ioniz.txt',
                        'output/Hydro_ioniz_IC.txt')
        shutil.copyfile('output/Ion_species.txt',
                        'output/Ion_species_IC.txt')
```

[Lines 253 and 254](https://github.com/ladsantos/p-winds/blob/a829f1c837d7ae279b6db0282d227acd0b7b0fd0/p_winds/fluid.py#L252-L254) then try and access those files: 
```
output_data_0 = np.loadtxt(_ATES_DIR + "/output/Hydro_ioniz.txt")
output_data_1 = np.loadtxt(_ATES_DIR + "/output/Ion_species.txt")
```

However, lines 253 and 254 assume that you are running the python script that imports **fluid.py** in `_ATES_DIR` (since it is trying to access the files created in lines 239-243, where no path is specified other than the "output" directory). 

If you want to run the python script that imports **fluid.py** in a separate directory (as I was), it might be helpful to rewrite lines 253 and 254 to be something like: 
```
current_file_path = os.getcwd()
output_data_0 = np.loadtxt(current_file_path + "/output/Hydro_ioniz.txt")
output_data_1 = np.loadtxt(current_file_path + "/output/Ion_species.txt")
```

This would allow the user to load the files that were saved in their current working directory, without having to be in their _ATES_DIR. Also, I have tested this and it worked for me in the beta version! There might be a nicer way to code it up though than what I wrote above.

**Comment by ladsantos** [comment]
This suggestion was implemented in [24ae0eb](https://github.com/ladsantos/p-winds/commit/24ae0eb60247bff61c17c8cc65989da1719c5a29). Thanks, @mls1052!
